dist: focal
sudo: false

language: go

go:
  - "1.15"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - gccgo
    - gfortran
    - libnlopt-dev

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=cover.out ./...

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
